collections:
  - name: ansible.posix
  - name: awx.awx
  - name: containers.podman
  - name: community.crypto
  - name: community.general
  - name: community.okd
  - name: kubernetes.core
    version: 5.1.0
  - name: redhat_cop.tower_configuration
roles:
  - src: https://github.com/hhue13/k8slogin.git
    scm: git
    version: main
    name: k8slogin
